# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protos/DotaOptimizer.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import protos.DotaOptimizer_pb2


class DotaOptimizerBase(abc.ABC):

    @abc.abstractmethod
    async def Rollout(self, stream):
        pass

    @abc.abstractmethod
    async def GetWeights(self, stream):
        pass

    def __mapping__(self):
        return {
            '/DotaOptimizer/Rollout': grpclib.const.Handler(
                self.Rollout,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.DotaOptimizer_pb2.RolloutData,
                protos.DotaOptimizer_pb2.Empty2,
            ),
            '/DotaOptimizer/GetWeights': grpclib.const.Handler(
                self.GetWeights,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.DotaOptimizer_pb2.Empty2,
                protos.DotaOptimizer_pb2.Weights,
            ),
        }


class DotaOptimizerStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Rollout = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DotaOptimizer/Rollout',
            protos.DotaOptimizer_pb2.RolloutData,
            protos.DotaOptimizer_pb2.Empty2,
        )
        self.GetWeights = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DotaOptimizer/GetWeights',
            protos.DotaOptimizer_pb2.Empty2,
            protos.DotaOptimizer_pb2.Weights,
        )
