# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import ModelService_pb2 as protos_dot_ModelService__pb2


class ModelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PutWeights = channel.unary_unary(
        '/ModelService/PutWeights',
        request_serializer=protos_dot_ModelService__pb2.Weights.SerializeToString,
        response_deserializer=protos_dot_ModelService__pb2.Empty2.FromString,
        )
    self.GetWeights = channel.unary_unary(
        '/ModelService/GetWeights',
        request_serializer=protos_dot_ModelService__pb2.WeightQuery.SerializeToString,
        response_deserializer=protos_dot_ModelService__pb2.Weights.FromString,
        )


class ModelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PutWeights(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWeights(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PutWeights': grpc.unary_unary_rpc_method_handler(
          servicer.PutWeights,
          request_deserializer=protos_dot_ModelService__pb2.Weights.FromString,
          response_serializer=protos_dot_ModelService__pb2.Empty2.SerializeToString,
      ),
      'GetWeights': grpc.unary_unary_rpc_method_handler(
          servicer.GetWeights,
          request_deserializer=protos_dot_ModelService__pb2.WeightQuery.FromString,
          response_serializer=protos_dot_ModelService__pb2.Weights.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ModelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
