# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protos/ModelService.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import protos.ModelService_pb2


class ModelServiceBase(abc.ABC):

    @abc.abstractmethod
    async def PutWeights(self, stream):
        pass

    @abc.abstractmethod
    async def GetWeights(self, stream):
        pass

    def __mapping__(self):
        return {
            '/ModelService/PutWeights': grpclib.const.Handler(
                self.PutWeights,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.ModelService_pb2.Weights,
                protos.ModelService_pb2.Empty2,
            ),
            '/ModelService/GetWeights': grpclib.const.Handler(
                self.GetWeights,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.ModelService_pb2.WeightQuery,
                protos.ModelService_pb2.Weights,
            ),
        }


class ModelServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.PutWeights = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ModelService/PutWeights',
            protos.ModelService_pb2.Weights,
            protos.ModelService_pb2.Empty2,
        )
        self.GetWeights = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ModelService/GetWeights',
            protos.ModelService_pb2.WeightQuery,
            protos.ModelService_pb2.Weights,
        )
